checks:
  complex-logic:
      config:
        threshold: 4
    file-lines:
      config:
        threshold: 250
    method-complexity:
      config:
        threshold: 5
plugins:
  eslint:
    enabled: true
    channel: "eslint-4"
    config:
      config: .eslintrc.json