version: "2"
prepare:
  fetch:
    - url: "https://raw.githubusercontent.com/example/example/master/rubocop.yml"
      path: "alternate-rubocop-path.yml"
checks:
  complex-logic:
    config:
      threshold: 4
  method-complexity:
    config:
      threshold: 20
plugins:
  eslint:
    enabled: true
    channel: "eslint-4"
    config:
      config: .eslintrc.json
