version: "2"
checks:
  complex-logic:
    config:
      threshold: 4
  method-complexity:
    config:
      threshold: 20
plugins:
  eslint:
    enabled: true
    channel: "eslint-4"
    config:
      config: .eslintrc.json
