version: '3'
services:
  app:
    build: .
    ports:
      - 19000:19000
      - 19001:19001
    volumes:
      - .:/app
    working_dir: /app/MasterGrimoire
    command: yarn start
    network_mode: "host"
